language: generic
require: sudo
services:
  - docker

before_install:
  - docker build -t gbrbd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gbrbd/react-test npm test

after_success:
  - docker build -t gbrbd/multi-client ./client
  - docker build -t gbrbd/multi-nginx ./nginx
  - docker build -t gbrbd/multi-server ./server
  - docker build -t gbrbd/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gbrbd/multi-client
  - docker push gbrbd/multi-nginx
  - docker push gbrbd/multi-server
  - docker push gbrbd/multi-worker
